language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
#  - zip -r 3tree-backend *
#  - mkdir -p deploy # zip 에 포함시킬 파일들을 담을 디렉토리 생성2
#  - mv 3tree-backend.zip deploy/3tree-backend.zip
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/3tree-backend.zip # deploy 로 zip 파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: 3tree-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private로
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ziptalk/3tree-backend
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: 3tree-springboot-build
    key: 3tree-backend.zip
    bundle_type: zip
    application: 3tree-ver2
    deployment_group: 3tree-ver2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: ziptalk/3tree-backend
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - pek2234@icloud.com
      - gkrry27232@naver.com