version: 0.0
os: linux
files:
  - source:   /
    destination: /home/ec2-user/app/travis/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall: #현재 단계에서 stop.sh 스크립트 파일을 실행시켜서 실행 중이던 스프링 부트 jar를 종료시킵니다.
    - location: stop.sh
      timeout: 60
      runas: root
  ApplicationStart: #현재 단계에서 stop.sh 스크립트 파일을 실행시켜서 실행 중이던 스프링 부트 jar를 종료시킵니다.
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService: #health.sh 스크립트 파일을 통해서 현재 jar가 잘 실행 중인지 체크를 합니다.
    - location: health.sh
      timeout: 60
      runas: root